# Generated by Django 3.0.3 on 2020-03-25 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genrer',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.FileField(default='', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(help_text='album name', max_length=100),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='song title', max_length=100)),
                ('artist', models.CharField(help_text='song artist', max_length=100)),
                ('genre', models.CharField(help_text='song genre', max_length=20)),
                ('sfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'aac'])])),
                ('image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('a1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
    ]
